### ISSUE TITLE
Set up ProxySQL between MariaDB "Galaxia" Galera Cluster and Strapi

### ISSUE THREAD

**Issue by jzanecook** [KBVE/kbve.com#10]

**Comment by h0lybyte** [comment]
https://severalnines.com/blog/how-run-and-configure-proxysql-20-mysql-galera-cluster-docker

They break it down fairly well, I think we should do something similar to that.

**Comment by h0lybyte** [comment]
In the guide they are using a wordpress container / docker, I would assume we "alex jones pepe gray frogs" the strapi where they use wordpress. With all respect and prayers to Clippy, we should be sucessful.

**Comment by h0lybyte** [comment]
![Error Ref 1](https://i.imgur.com/h9JlW1v.png)
![Error Ref 2](https://i.imgur.com/GAjYQ8W.png)

Might be from the storage driver change on docker1058 / docker1059.

Let me see if I can change the driver = local to another driver.

**Comment by h0lybyte** [comment]
![Error Ref 3](https://i.imgur.com/6RKzAar.png)

Okay looks like we did use all the space, which is weird, I am assuming there are a lot of dead containers / vols sitting around.

**Comment by h0lybyte** [comment]
```
yarn run v1.22.19
$ strapi start
[2022-09-19 05:07:00.456] debug: ⛔️ Server wasn't able to start properly.
[2022-09-19 05:07:00.458] error: getaddrinfo ENOTFOUND /run/secrets/DATABASE_HOST
Error: getaddrinfo ENOTFOUND /run/secrets/DATABASE_HOST
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    --------------------
    at Protocol._enqueue (/api/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/api/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/api/node_modules/mysql/lib/Connection.js:116:18)
    at /api/node_modules/knex/lib/dialects/mysql/index.js:66:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (/api/node_modules/knex/lib/dialects/mysql/index.js:61:12)
    at create (/api/node_modules/knex/lib/client.js:252:39)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
Error log before I start doing some experimental concepts.

**Comment by h0lybyte** [comment]
```
[2022-09-19 05:35:22.056] debug: ⛔️ Server wasn't able to start properly.
[2022-09-19 05:35:22.059] error: connect ECONNREFUSED 10.x.x.x:3306
Error: connect ECONNREFUSED 10.x.x.x:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
    --------------------
    at Protocol._enqueue (/api/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/api/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/api/node_modules/mysql/lib/Connection.js:116:18)
    at /api/node_modules/knex/lib/dialects/mysql/index.js:66:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (/api/node_modules/knex/lib/dialects/mysql/index.js:61:12)
    at create (/api/node_modules/knex/lib/client.js:252:39)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
Ahhh connection refused.

**Comment by h0lybyte** [comment]
https://betterprogramming.pub/how-to-handle-docker-secrets-in-node-js-3aa04d5bf46e

**Comment by h0lybyte** [comment]
Now we have to build out the weights for the proxy sql. Going to use [3] as a reference point and then later on integrate it all into https://kbve.com/application/proxysql 


[3] https://proxysql.com/documentation/backend-server-configuration/

**Comment by h0lybyte** [comment]
This is not yet resolved, ProxySQL is balancing the SQL management amoung 4 + N different data locations:
1 - [OVH]
 - - > Self Deployed MySQL Server for Read* only, so no remote connection hop has to be made.
2 - [Amazon]
- - > Handling the Master Write A
3 - [Google}
- - > Handling the Master Write B
4 - [Lab] + N [Labs].
- - > Handling Reads B .... ect.


We have 3 Primary Writer/Master SQLs. First is on OVH, 2nd is on AWS and 3rd is Google. With several <Read>/<Slaves>. This has taken us some time to build out but we should be ready to move this torwards a full production scale. I will keep this ticket open until all of it can be fully automated, from backup to reproduction.

**Comment by h0lybyte** [comment]
Currently one of the problems that we are facing is a write latency between the master node and slave node. There is a weird way that we currently fixed it but that was using two master nodes, which is not recommended as it can break quorum. 

M1-Master- READ/WRITE
M2-Master (replica) - READ/WRITE - shared filesystem with M1 and helps avoid the lockfile issue. 
M0-Slave - Written to by M2-Master.
Slaves-N - Cluster of M0-Slave instances that are read-only.

**Comment by h0lybyte** [comment]
Automating Tasker
* * *
[KBVE Support](https://kbve.com/support/)
* * *
[KBVE Discord](https://kbve.com/discord/)
* * *
[KBVE Staff](https://kbve.com/team/)
* * *
[KBVE VIP Priority](https://kbve.com/vip/) || [KBVE Community](https://kbve.com/c/)
* * *
[HubSpot Ticket Created](https://app.hubspot.com/contacts/20854121/ticket/1514265620)
* * *
