### ISSUE TITLE
GPU1 Project

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#27]
**Describe the bug**
Having issues with sending a postman to the GPU1.

```{
    "detail": [
        {
            "loc": [
                "body",
                "input",
                "prompt_strength"
            ],
            "msg": "value is not a valid float",
            "type": "type_error.float"
        },
        {
            "loc": [
                "body",
                "input",
                "num_animation_frames"
            ],
            "msg": "value is not a valid integer",
            "type": "type_error.integer"
        },
        {
            "loc": [
                "body",
                "input",
                "num_interpolation_steps"
            ],
            "msg": "value is not a valid integer",
            "type": "type_error.integer"
        },
        {
            "loc": [
                "body",
                "input",
                "gif_frames_per_second"
            ],
            "msg": "value is not a valid integer",
            "type": "type_error.integer"
        },
        {
            "loc": [
                "body",
                "input",
                "gif_ping_pong"
            ],
            "msg": "value could not be parsed to a boolean",
            "type": "type_error.bool"
        },
        {
            "loc": [
                "body",
                "input",
                "film_interpolation"
            ],
            "msg": "value could not be parsed to a boolean",
            "type": "type_error.bool"
        },
        {
            "loc": [
                "body",
                "input",
                "intermediate_output"
            ],
            "msg": "value could not be parsed to a boolean",
            "type": "type_error.bool"
        },
        {
            "loc": [
                "body",
                "input",
                "seed"
            ],
            "msg": "value is not a valid integer",
            "type": "type_error.integer"
        },
        {
            "loc": [
                "body",
                "input",
                "output_format"
            ],
            "msg": "value is not a valid enumeration member; permitted: 'gif', 'mp4'",
            "type": "type_error.enum",
            "ctx": {
                "enum_values": [
                    "gif",
                    "mp4"
                ]
            }
        }
    ]
}```
* * *

**Comment by jzanecook** [comment]
See [their demo site](https://replicate.com/andreasjansson/stable-diffusion-animation) for some default values

**Comment by h0lybyte** [comment]
```
{"input": {
    "prompt_start": "There was a fish that ate a man.",
    "prompt_end": "The fish was a god.",
    "width": "512",
    "height": "512",
    "num_inference_steps": "50",
    "prompt_strength": "0.9",
    "num_animation_frames": "25",
    "num_interpolation_steps": "5",
    "guidance_scale": "7.5",
    "gif_frames_per_second": "20",
    "gif_ping_pong": true,
    "film_interpolation": true,
    "intermediate_output": false,
    "seed": "kbve",
    "output_format": "mp4"
  }}
  ```

**Comment by h0lybyte** [comment]
```
Your kernel may have been built without NUMA support.
2022-09-08 00:50:12.695132: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1644 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1]
INFO:     Started server process [1]
INFO:     Waiting for application startup.
Loading pipeline...
2022-09-11 07:12:31.406961: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-09-11 07:12:31.573794: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-09-11 07:12:31.574067: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
Loading interpolator...
2022-09-11 07:12:32.145671: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-11 07:12:32.149881: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-09-11 07:12:32.150230: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-09-11 07:12:32.150456: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-09-11 07:12:32.155587: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-09-11 07:12:32.156256: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-09-11 07:12:32.156465: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1609] Could not identify NUMA node of platform GPU id 0, defaulting to 0.  Your kernel may not have been built with NUMA support.
2022-09-11 07:12:32.156659: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-09-11 07:12:32.158153: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1644 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
Using seed: 5283
Generating initial latents for 4 steps
Generating first frame
Generating last frame
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
INFO:     172.17.0.1:60730 - "POST /predictions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/http.py", line 83, in predict
    response = Response(status=Status.SUCCEEDED, output=output)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1056, in pydantic.main.validate_model
  File "pydantic/fields.py", line 857, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1074, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 313, in pydantic.class_validators._generic_validator_basic.lambda12
  File "pydantic/main.py", line 704, in pydantic.main.BaseModel.validate
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1056, in pydantic.main.validate_model
  File "pydantic/fields.py", line 868, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 899, in pydantic.fields.ModelField._validate_sequence_like
  File "/src/predict_animate.py", line 172, in predict
    self.pipe.safety_check(image_end)
  File "/src/animate.py", line 172, in safety_check
    raise Exception("NSFW content detected, please try a different prompt and/or seed")
Exception: NSFW content detected, please try a different prompt and/or seed
```

**Comment by h0lybyte** [comment]
```
{"input": {
    "prompt_start": "There was a fish that swam with a bear.",
    "prompt_end": "The fish was a ruler.",
    "width": 128,
    "height": 128,
    "num_inference_steps": 50,
    "prompt_strength": 0.9,
    "num_animation_frames": 25,
    "num_interpolation_steps": 5,
    "guidance_scale": 7.5,
    "gif_frames_per_second": 20,
    "gif_ping_pong": true,
    "film_interpolation": true,
    "intermediate_output": false,
    "seed": null,
    "output_format": "mp4"
  }}
  ```

**Comment by h0lybyte** [comment]
I will close up this issue for now. It seems we do not have enough GPU memory within our edge stack(s). 

This will be something that we can look into later down the line.
