### ISSUE TITLE
Strapi - Dev Mode - Alter Table Error

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#44]
**Describe the bug**

```
]
[2022-09-20 22:50:37.419] debug: ⛔️ Server wasn't able to start properly.
[2022-09-20 22:50:37.421] error: alter table `strapi_webhooks` modify `headers` json null, modify `events` json null - EE_WRITE: Error writing file './apistrapi/#sql-22_9fb.frm' (Errcode: 28 "No space left on device")
Error: EE_WRITE: Error writing file './apistrapi/#sql-22_9fb.frm' (Errcode: 28 "No space left on device")
    at Query.Sequence._packetToError (C:\Users\kbvec\Documents\api.kbve.com\api\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\kbvec\Documents\api.kbve.com\api\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\kbvec\Documents\api.kbve.com\api\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\kbvec\Documents\api.kbve.com\api\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\kbvec\Documents\api.kbve.com\api\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\kbvec\Documents\api.kbve.com\api\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\kbvec\Documents\api.kbve.com\api\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\kbvec\Documents\api.kbve.com\api\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (C:\Users\kbvec\Documents\api.kbve.com\api\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\kbvec\Documents\api.kbve.com\api\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\kbvec\Documents\api.kbve.com\api\node_modules\knex\lib\dialects\mysql\index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (C:\Users\kbvec\Documents\api.kbve.com\api\node_modules\knex\lib\dialects\mysql\index.js:126:12)
    at executeQuery (C:\Users\kbvec\Documents\api.kbve.com\api\node_modules\knex\lib\execution\internal\query-executioner.js:37:17)
    at Client_MySQL.query (C:\Users\kbvec\Documents\api.kbve.com\api\node_modules\knex\lib\client.js:146:12)
    at C:\Users\kbvec\Documents\api.kbve.com\api\node_modules\knex\lib\execution\transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (C:\Users\kbvec\Documents\api.kbve.com\api\node_modules\knex\lib\execution\transaction.js:358:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

It created the file -> ` \users-permissions\content-types\user\schema.json `

Below is the json file

* * * 

```json
{
  "kind": "collectionType",
  "collectionName": "up_users",
  "info": {
    "name": "user",
    "description": "",
    "singularName": "user",
    "pluralName": "users",
    "displayName": "User"
  },
  "options": {
    "draftAndPublish": false,
    "timestamps": true
  },
  "attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "unique": true,
      "configurable": false,
      "required": true
    },
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": true
    },
    "provider": {
      "type": "string",
      "configurable": false
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "configurable": false,
      "private": true
    },
    "resetPasswordToken": {
      "type": "string",
      "configurable": false,
      "private": true
    },
    "confirmationToken": {
      "type": "string",
      "configurable": false,
      "private": true
    },
    "confirmed": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "blocked": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "role": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "plugin::users-permissions.role",
      "inversedBy": "users",
      "configurable": false
    },
    "data": {
      "type": "json"
    }
  }
}

```

It did add the data but then failed to run again locally, crashing and giving that error. 

* * *

**Comment by h0lybyte** [comment]
It seems that one of the dbs inside the cluster actually ran out of space. 

I was able to resolve it, to an extent, but I am thinking that it could be a bigger problem down the line. We should add another 2-3 worker nodes into our setup but with more harddrive space and ram; we need some big boiii workers.
