### ISSUE TITLE
Concept: reCaptcha / hCaptcha / Registration Protection

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#52]
**Core Concept/Theory**
As we test the registration method, one of the issues that we need to address would be the captcha. 

* * *

**Alternative Ideas**
Option A: `reCaptcha`
Option B: `hCaptcha`

* * *

**Comment by h0lybyte** [comment]
[1] https://docs.strapi.io/developer-docs/latest/development/plugins-extension.html#within-the-extensions-folder
[2] https://forum.strapi.io/t/how-to-override-users-permissions-on-v4/15437

**Comment by h0lybyte** [comment]
```
[2022-09-26 22:13:00.263] http: GET login.html (6 ms) 200
[2022-09-26 22:13:04.595] http: POST /documentation/login (90 ms) 302
  Error: Cannot send secure cookie over unencrypted connection
      at Cookies.set (/api/node_modules/cookies/index.js:94:11)
      at ContextSession.save (/api/node_modules/koa-session/lib/context.js:339:22)
      at ContextSession.commit (/api/node_modules/koa-session/lib/context.js:239:16)
      at session (/api/node_modules/koa-session/index.js:46:20)
      at async /api/node_modules/@strapi/strapi/lib/services/metrics/middleware.js:29:5
[2022-09-26 22:13:07.207] http: GET login.html (5 ms) 200
[2022-09-26 22:13:10.560] http: GET /documentation (3 ms) 302
[2022-09-26 22:13:10.623] http: GET login.html (7 ms) 200
[2022-09-26 22:13:15.507] http: POST /documentation/login (88 ms) 302
  Error: Cannot send secure cookie over unencrypted connection
      at Cookies.set (/api/node_modules/cookies/index.js:94:11)
      at ContextSession.save (/api/node_modules/koa-session/lib/context.js:339:22)
      at ContextSession.commit (/api/node_modules/koa-session/lib/context.js:239:16)
      at session (/api/node_modules/koa-session/index.js:46:20)
      at async /api/node_modules/@strapi/strapi/lib/services/metrics/middleware.js:29:5
      
```
I noticed this error when messing around with the documentation lock. I am going to merge this issue with the current issue. There might be a setting / feature that I missed when setting up the api.

**Comment by h0lybyte** [comment]
Hand this back over to me after the register component is done. This way we are not over lapping.

**Comment by h0lybyte** [comment]
https://i.imgur.com/lNZNCZP.png

Okay so registeration works, there seems to be an issue with the response error / handling from the server side.

I think there should be a small react component that opens up saying "Registering..." with a fake delay of `500ms<t<2000ms` that gives time in between clicking the "Sign up" and then getting back the JWT (upon success) ~

Also  that was there -> not too sure what it meant. 

```
[DOM] Input elements should have autocomplete attributes (suggested: "new-password"): (More info: https://goo.gl/9p2vKq) <input aria-invalid=​"false" id=​"confirm-password-input" type=​"password" class=​"MuiInputBase-input MuiOutlinedInput-input css-1t8l2tu-MuiInputBase-input-MuiOutlinedInput-input" value>​
react-dom.development.js:29840 
```

**Comment by h0lybyte** [comment]
For cookies, shall we use https://www.npmjs.com/package/react-cookie ?

**Comment by jzanecook** [comment]
Yes, the react-cookie library looks great.

**Comment by h0lybyte** [comment]
I will close this and isolate each of the issues as their own.
